### ISSUE TITLE
Arrival and Departure Data Not Updating in Modal When Selecting Another Stop

### ISSUE THREAD

**Issue by Ahmedhossamdev** [OneBusAway/wayfinder#93] opened 2024-11-01 08:00 UTC
https://github.com/user-attachments/assets/1ceff57f-e6ad-4ca0-9152-c61aa981e69a

**Comment by tarunsinghofficial** [comment] 2024-11-01 08:07
Hi @Ahmedhossamdev,

It's not a bug, but we haven't implemented that feature yet. Currently, it works by only closing one stop and opening another :)

**Comment by Ahmedhossamdev** [comment] 2024-11-01 08:18
Hey @tarunsinghofficial 

Cool, thanks for the clarification. I had no idea that it was not implemented, but as a user, I will notice that something went wrong, so I will add it as an issue.

**Closed** 2024-11-01 23:24 UTC
